apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
data:
  SPRING_PROFILES_ACTIVE:  "docker"
  CATALOG_SERVICE_URL: "http://catalog-service:8081"
  ORDER_SERVICE_URL: "http://order-service:8082"
  MANAGEMENT_TRACING_ENABLED: "true"
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: "http://tempo:9411"